name: Auto Assignment

on:
    pull_request:
        types: [opened]

jobs:
    assignment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.0.1
            - uses: kyoya0819/auto-assignment@v1.2.2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  users: '["mushlih-almubarak"]'
